# Tutorial: Discrete Dynamic Programming

## Advanced Macro: numerical methods

## Markov Chains

A worker’s employment dynamics obey the stochastic matrix

$$P = \begin{bmatrix}
1-\alpha & \alpha \\
\beta & 1-\beta
\end{bmatrix}$$



$$P = \begin{bmatrix}
1-\alpha & ... \\
\beta & ...
\end{bmatrix}$$


with $\alpha\in(0,1)$ and $\beta\in (0,1)$. First line corresponds to employment, second line to unemployment.

__Which is the stationary equilibrium?__

In [30]:
# Let's choose α and β
α = 0.05 # probability of becoming unemployed if you were initially employed
β = 0.2  # probability of finding a job if you are unemployed 

0.2

In [31]:
P = [ 1-α α ; β 1-β ]

2×2 Array{Float64,2}:
 0.95  0.05
 0.2   0.8

In [32]:
# we want to find mu such that sum(\mu) = 1 and \mu' * P = \mu


In [33]:
using LinearAlgebra

In [34]:
M = (P' - I)

2×2 Array{Float64,2}:
 -0.05   0.2
  0.05  -0.2

In [35]:
# the lines are not independent from each other:
#if   (-0.05)*x +   0.2  y = 0
#then ( 0.05)*x + (-0.2) y = 0

In [36]:
rhs = zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [37]:
# I want M*μ=rhs

In [38]:
M\rhs # exactly equivalent to solve(M, rhs)

2-element Array{Float64,1}:
 -0.0
 -0.0

In [39]:
det(M)

5.551115123125788e-18

In [40]:
# there isn't one single solution

In [41]:
M[1,:] .= 1
M

2×2 Array{Float64,2}:
 1.0    1.0
 0.05  -0.2

In [42]:
rhs[1] = 1

1

In [43]:
μ=M\rhs

2-element Array{Float64,1}:
 0.7999999999999999
 0.20000000000000007

In [44]:
μ'*P

1×2 Adjoint{Float64,Array{Float64,1}}:
 0.8  0.2

In [46]:
# alternattive approach

In [47]:
W = P'-I

2×2 Array{Float64,2}:
 -0.05   0.2
  0.05  -0.2

In [53]:
W = [ones(1,2); P' - I]

3×2 Array{Float64,2}:
  1.0    1.0
 -0.05   0.2
  0.05  -0.2

In [54]:
Rhs = [1.0, 0, 0]

3-element Array{Float64,1}:
 1.0
 0.0
 0.0

In [ ]:
W * μ = Rhs

In [55]:
μ = W\Rhs # this is not a matrix inversion, it is a square minimizatin problem
# it minimizes sum((W*\mu - Rhs)^2)

2-element Array{Float64,1}:
 0.7999999999999993
 0.2000000000000005

__In the long run, what will the the fraction $p$ of time spent unemployed? (Denote by $X_m$ the fraction of dates were one is unemployed)__

__Illustrate this convergence by generating a simulated series of length 10000 starting at $X_0=1$. Plot $X_m-p$ against $m$. (Take $\alpha=\beta=0.1$).__

## Basic Asset Pricing model

A financial asset yields dividend $(x_t)$, which follows an AR1. It is evaluated using the stochastic discount factor: $\rho_{0,t} = \beta^t \exp(y_t)$  where $\beta<1$ and $y_t$ is an $AR1$.
The price of the asset is given by $p_0 = \sum_{t\geq 0} \rho_{0,t} U(x_t)$ where $U(u)=\exp(u)^{0.5}/{0.5}$.
Our goal is to find the pricing function $p(x,y)$, which yields the price of the asset in any state.

__Write down the recursive equation which must be satisfied by $p$.__

__Discretize processes $(x_t)$ and $(y_t)$ using 2 states each. How would you represent the unknown $p()$?__

__Solve for $p()$ using successive approximations__

__Solve for $p()$ by solving a linear system (homework)__

## Asset replacement (from Compecon)

At the beginning of each year, a manufacturer must decide whether to continue to operate an aging physical asset or replace it with a new one.

An asset that is $a$ years old yields a profit contribution $p(a)$ up to $n$ years, at which point, the asset becomes unsafe and must be replaced by law.

The cost of a new asset is $c$. What replacement policy maximizes profits?

Calibration: profit $p(a)=50-2.5a-2.5a^2$. Maximum asset age: 5 years. Asset replacement cost: 75, annual discount factor $\delta=0.9$.

__Define kind of problem, the state space, the actions, the reward function, and the Bellman updating equation__

__Solve the problem using Value Function Iteration__

__Solve the problem using Policy Iteration. Compare with VFI.__

### Brock-Mirman Stochastic Growth model

This is a neoclassical growth model with unpredictable shocks on productivity.

Social planner tries to solve:

$$\max E_t \left[ \sum_{n=0}^{\infty} \beta^n \log C_{t+n} \right]$$

s.t.

$$K_{t+1} = Y_t - C_t$$
$$Y_{t+1} = A_{t+1}K_{t+1}^\alpha$$

where $A_t$ is the level of productivity in period $t$. 
It can take  values $A^h=1.05$ and $A^l=0.95$. The transition between these two states are given by the matrix:
$$P = \begin{bmatrix}
0.9, 0.1\\
0.1, 0.9
\end{bmatrix}$$

__Propose a plausible calibration__

__What are the states? What are the controls? Is it possible to bound them in a natural way? Propose a discretization scheme.__

__Write down the Bellman equation__

__How do you represent a policy function? Implement a value evaluation function.__

__Solve the model using Value Function Iteration. Plot the solution.__

__Implement Policy Improvement Steps. Compare convergence Speed.__

__Bonus: Propose some ideas to improve performances.__

Note: the remaining allocations are due to the function `distance`, which allocates a Float64 for its output.